---
- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Rebuild initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true
