---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload and restart mqtt services
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart mqtt-led
